
public class DataConstants {
  protected static final String FILE_PATH = "CSCE247/LanguageLearningApp/json/user.json";
  protected static final String USER_ID = "uuid";
  protected static final String USER_FIRST_NAME = "first-name";
  protected static final String USER_LAST_NAME = "last-name";
  protected static final String USER_USERNAME = "username";
  protected static final String USER_EMAIL = "email";
  protected static final String USER_PASSWORD = "password";
  protected static final String USER_LANGUAGES = "languages";
  protected static final String LANGUAGE_DIFFICULTY = "difficulty";
  protected static final String EASY = "EASY";
  protected static final String MEDIUM = "MEDIUM";
  protected static final String HARD = "HARD";
  protected static final String FOREIGN_LANGUAGE = "foreign-language";
  protected static final String USER_SETTINGS = "user-settings";
  protected static final String USER_NOTIFICATIONS = "notifications";
  protected static final String USER_LIGHT_MODE = "light-mode";
  protected static final String USER_TEXT_TO_SPEECH = "text-to-speech";
  protected static final String USER_FONT_SIZE = "font-size";
  protected static final String USER_FRIENDS = "friends";
  protected static final String LESSONS_COMPLETED = "lessons-completed";
  protected static final String SPANISH = "SPANISH";
  protected static final String LESSONS = "lessons";
  protected static final String QUESTIONS = "questions";
  protected static final String QUESTIONTYPE = "questiontype";
  protected static final String PROMPT = "prompt";
  protected static final String ANSWER = "answer";
  protected static final String FLASHCARD= "flashcard";
  protected static final String MATCHING = "matching";
  protected static final String STORY = "story";
  protected static final String MULTIPLECHOICE = "multiplechoice";
  protected static final String FILLBLANK = "fillblank";
  protected static final String SCHOOL = "school";
  protected static final String FAMILY = "family";
  protected static final String WEATHER = "weather";
  protected static final String PETS = "pets";
  protected static final String FOOD = "food";
}
